### ISSUE TITLE
No dropdown icon on top menu mode

### ISSUE THREAD

**Issue by adiramardiani** [vbenjs/vue-vben-admin#1274]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

On navigation menu I think menu who have sub menu should use dropdown icon (arrow down), only for one level menu not show dropdown icon

### Reproduction

Currently check on live url https://vvbin.cn/next/#/dashboard/analysis

![image](https://user-images.githubusercontent.com/8703419/136647499-dafa3702-54c8-4e23-a335-2b9c2b3449bc.png)

**Comment by wangjue666** [comment]
Yes, because Antd's menu component does not support， 

If you add a dropdown icon through slot, if the length of the menu element is too long, the menu will change to another style.

The difficulty lies in the inability to recognize whether it is in the thumbnail style.

![1697877570787](https://github.com/vbenjs/vue-vben-admin/assets/24707417/75f06fb3-1c0c-4d69-a53d-328cd65106a2)


https://www.antdv.com/components/menu-cn
